package com.utn.frsf.Enums;

public enum CondicionIva {
    RESPONSABLE_INSCRIPTO,
    RESPONSABLE_NO_INSCRIPTO,
    NO_RESPONSABLE,
    SUJETO_EXENTO,
    CONSUMIDOR_FINAL,
    RESPONSABLE_MONOTRIBUTO,
    SUJETO_NO_CATEGORIZADO,
    IVA_LIBERADO,
    MONOTRIBUTISTA_SOCIAL
}
